# Generated by Django 4.2.5 on 2023-10-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_drinks', '0002_drink_description_drink_promotion_price_and_more'),
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_drinks.drink'),
        ),
    ]
