# Generated by Django 4.2.5 on 2023-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drinks', '0002_drink_description_drink_promotion_price_and_more'),
        ('app_general', '0003_rename_food_subscription_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='drink',
        ),
        migrations.AddField(
            model_name='subscription',
            name='drink_set',
            field=models.ManyToManyField(to='app_drinks.drink'),
        ),
    ]
