# Generated by Django 4.2.5 on 2023-10-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_remove_subscription_drink_subscription_drink_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='drink_set',
            new_name='drinks_set',
        ),
    ]
