# Generated by Django 4.2.5 on 2023-10-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_rename_drink_set_subscription_drinks_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='drinks_set',
            new_name='drink_set',
        ),
    ]
