# Generated by Django 4.2.5 on 2023-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='promotion_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
